import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import svgstore from 'svgstore';
import { optimize } from 'svgo';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const logosDir = path.resolve(__dirname, '..', 'assets', 'svg-purple-logos');
const outDir = path.resolve(__dirname, '..', 'assets');
const spriteFile = path.join(outDir, 'sprite.svg');
const inlineScriptFile = path.join(outDir, 'sprite-inline.js');

const files = readdirSync(logosDir)
  .filter((file) => file.toLowerCase().endsWith('.svg'))
  .sort();

if (!files.length) {
  console.error(`No SVG files found in ${logosDir}`);
  process.exit(1);
}

const sprite = svgstore({ inline: true });

files.forEach((file) => {
  const raw = readFileSync(path.join(logosDir, file), 'utf8');
  const optimized = optimize(raw, {
    multipass: true,
    plugins: [
      'preset-default',
      {
        name: 'removeXMLNS',
      },
    ],
  });

  const id = file
    .replace(/\.svg$/i, '')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();

  sprite.add(id, optimized.data);
});

mkdirSync(outDir, { recursive: true });
const spriteMarkup = sprite.toString({ inline: true });
writeFileSync(spriteFile, spriteMarkup, 'utf8');

const inlineMarkup = spriteMarkup.replace(
  '<svg',
  '<svg id="svg-sprite-inline" aria-hidden="true" focusable="false" style="position:absolute;width:0;height:0;overflow:hidden;"'
);

const inlineScript = `// Auto-generated by scripts/build-sprite.mjs. Do not edit manually.
(function injectSprite() {
  if (document.getElementById('svg-sprite-inline')) {
    return;
  }

  const template = document.createElement('template');
  template.innerHTML = ${JSON.stringify(inlineMarkup)};

  const insert = () => {
    const clone = template.content.cloneNode(true);
    const target = document.body || document.documentElement;
    target.insertBefore(clone, target.firstChild || null);
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', insert, { once: true });
  } else {
    insert();
  }
})();`;

writeFileSync(inlineScriptFile, inlineScript, 'utf8');

console.log(`SVG sprite created at ${spriteFile}`);
console.log(`Inline sprite helper created at ${inlineScriptFile}`);
